version: '3.9'

services:
  app:
    image: cooderl/wewe-rss-sqlite:latest
    ports:
      - 4000:4000
    environment:
      # 数据库连接地址
      # - DATABASE_URL=file:../data/wewe-rss.db
      - DATABASE_TYPE=sqlite
      # 服务接口请求授权码
      - AUTH_CODE=123567
      # 提取全文内容模式
      # - FEED_MODE=fulltext
      # 定时更新订阅源Cron表达式
      # - CRON_EXPRESSION=35 5,17 * * *
      # 服务接口请求限制，每分钟请求次数
      # - MAX_REQUEST_PER_MINUTE=60
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      # - SERVER_ORIGIN_URL=http://localhost:4000

    volumes:
      # 映射数据库文件存储位置，容器重启后不丢失
      - ./data:/app/data

  extensions:
    image: wynying92/wewe-rss-extensions:latest
    ports:
      - 4100:4100
    depends_on:
      - app
    environment:
      # 数据库连接地址，与app服务的DATABASE_URL保持一致，优先级低于CONF_PATH中的db_url
      - DATABASE_URL=file:../data/wewe-rss.db
      # 数据库类型 mysql/sqlite 与app服务的DATABASE_TYPE保持一致，优先级低于CONF_PATH中的db_provider
      - DATABASE_TYPE=sqlite
      # 所有Notifier默认的通知周期，优先级低于CONF_PATH中的default_interval_minutes
      - NOTIFY_INTERVAL_MINUTES=240
      # Notifier的配置文件路径
      - CONF_PATH=/app/data/conf/conf.yaml
    volumes:
      - ./data:/app/data
