version: '3.9'

services:
  db:
    image: mysql:8.3.0
    command: --mysql-native-password=ON
    environment:
      # 请修改为自己的密码
      MYSQL_ROOT_PASSWORD: 123456
      TZ: 'Asia/Shanghai'
      MYSQL_DATABASE: 'wewe-rss'
    volumes:
      - ./data/db:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      wewe-rss:

  app:
    image: cooderl/wewe-rss:latest
    ports:
      - 4000:4000
    depends_on:
      db:
        condition: service_healthy
    environment:
      # 数据库连接地址
      - DATABASE_URL=mysql://root:123456@db:3306/wewe-rss?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
      # 服务接口请求授权码
      - AUTH_CODE=123567
      # 提取全文内容模式
      # - FEED_MODE=fulltext
      # 定时更新订阅源Cron表达式
      # - CRON_EXPRESSION=35 5,17 * * *
      # 服务接口请求限制，每分钟请求次数
      # - MAX_REQUEST_PER_MINUTE=60
      # 外网访问时，需设置为服务器的公网 IP 或者域名地址
      # - SERVER_ORIGIN_URL=http://localhost:4000
    networks:
      wewe-rss:

  extensions:
    image: wynying92/wewe-rss-extensions:latest
    depends_on:
      db:
        condition: service_healthy
    environment:
      # 是否启用Notifier，任意非空值视为 启用，空值（ENABLE_NOTIFIER=）视为 不启用
      - ENABLE_NOTIFIER=1
      # 数据库连接地址，与app服务的DATABASE_URL保持一致，优先级低于NOTIFIER_CONF_PATH中的db_url
      - DATABASE_URL=mysql://root:123456@db:3306/wewe-rss?schema=public&connect_timeout=30&pool_timeout=30&socket_timeout=30
      # 数据库类型 mysql/sqlite 与app服务的DATABASE_TYPE保持一致，优先级低于NOTIFIER_CONF_PATH中的db_provider
      - DATABASE_TYPE=mysql
      # 所有Notifier默认的通知周期，优先级低于NOTIFIER_CONF_PATH中的default_interval_minutes
      - NOTIFY_INTERVAL_MINUTES=240
      # Notifier的配置文件路径
      - NOTIFIER_CONF_PATH=/app/data/conf/notify.yaml
    volumes:
      - ./data/conf:/app/data/conf
    networks:
      wewe-rss:

networks:
  wewe-rss:
